namespace Perpetuum.WikiGenerate;

/// <summary>Markdown table + page helpers shared by all page generators.</summary>
public static class Md
{
    /// <summary>Client string dictionary (key -> display name) loaded from the GBF
    /// archive; empty when no archive was supplied.</summary>
    public static Dictionary<string, string> ClientStrings { get; set; } = new();

    /// <summary>Escapes pipes and newlines for a single table cell.</summary>
    public static string Cell(object? v)
    {
        var s = Genxy.FormatValue(v);
        if (s.Length == 0) return "–";
        return s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
    }

    public static void WriteTable(StringBuilder sb, string[] header, params string[][] rows)
    {
        sb.Append('|');
        foreach (var h in header) sb.Append(' ').Append(h).Append(" |");
        sb.Append('\n');
        sb.Append('|');
        for (var i = 0; i < header.Length; i++) sb.Append("---|");
        sb.Append('\n');
        foreach (var row in rows)
        {
            sb.Append('|');
            foreach (var c in row) sb.Append(' ').Append(Cell(c)).Append(" |");
            sb.Append('\n');
        }
    }

    public static string Tier(int tierType, int? tierLevel)
    {
        if (tierLevel is null || tierLevel == 0) return tierType == 2 ? "prototype" : "";
        return tierLevel.ToString();
    }

    /// <summary>Standard page header. Provenance is a developer comment (invisible in the wiki).</summary>
    public static string Header(string title, string description, string source)
    {
        // Zola content front matter is YAML (not TOML). Titles can be client display
        // names, so escape the double-quoted scalar properly.
        return $$"""
            ---
            title: "{{Yaml(title)}}"
            description: "{{Yaml(description)}}"
            ---

            <!-- Generated by tools/generate from the live database (source: {{source}}).
                 Do not edit by hand; regenerate instead. -->
            """;
    }

    private static string Yaml(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Zone display name: the client's name where it has one, otherwise the
    /// internal zone name (gamma zones have no client name).</summary>
    public static string ZoneName(string name) => ClientStrings.TryGetValue(name, out var d) ? d : name;

    /// <summary>Player-readable name for an internal definition/zone name: the client's
    /// own string when the dictionary has it, otherwise derived from the internal name.
    /// forceDerived skips the dictionary (used when a client string collides with
    /// another item's name and the derived name is more informative).</summary>
    public static string DisplayName(string name, bool forceDerived = false)
    {
        if (!forceDerived && ClientStrings.TryGetValue(name, out var client)) return client;
        return Derive(name);
    }

    private static string Derive(string name)
    {
        if (name.StartsWith("def_")) name = name[4..];
        if (name.EndsWith("_bot")) name = name[..^4];
        name = name.Replace("_mk2", " MK2").Replace("_reward1", " (reward)").Replace("_CT_capsule", " (CT capsule)");
        var tokens = name.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Join(' ', tokens.Select(t => char.ToUpperInvariant(t[0]) + t[1..]));
    }
}

