namespace Perpetuum.WikiGenerate;

/// <summary>Markdown table + page helpers shared by all page generators.</summary>
public static class Md
{
    /// <summary>Client display names: a static snapshot of the official client's
    /// English string dictionary (see ClientNames.cs), reduced to the definition
    /// and zone keys this generator resolves.</summary>
    public static IReadOnlyDictionary<string, string> ClientStrings { get; } = ClientNames.Map;

    /// <summary>Escapes pipes and newlines for a single table cell.</summary>
    public static string Cell(object? v)
    {
        var s = Genxy.FormatValue(v);
        if (s.Length == 0) return "–";
        return s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
    }

    public static void WriteTable(StringBuilder sb, string[] header, params string[][] rows)
    {
        sb.Append('|');
        foreach (var h in header) sb.Append(' ').Append(h).Append(" |");
        sb.Append('\n');
        sb.Append('|');
        for (var i = 0; i < header.Length; i++) sb.Append("---|");
        sb.Append('\n');
        foreach (var row in rows)
        {
            sb.Append('|');
            foreach (var c in row) sb.Append(' ').Append(Cell(c)).Append(" |");
            sb.Append('\n');
        }
    }

    /// <summary>
    /// The tier column: the game's tierlevel shown as T1–T5 (the client's
    /// convention — def_elitet4_* is tierlevel 4, def_elitet2_* is 2), plus a
    /// series marker: prototype variants (tiertype 2) and special lines
    /// (tiertype 3: elite/artifact/faction lines).
    /// </summary>
    public static string Tier(int tierType, int? tierLevel)
    {
        if (tierLevel is null || tierLevel == 0)
            return tierType switch { 2 => "prototype", 3 => "special", _ => "" };
        return tierType switch
        {
            2 => $"T{tierLevel} (prototype)",
            3 => $"T{tierLevel} (special)",
            _ => $"T{tierLevel}"
        };
    }

    /// <summary>Standard page header. Provenance is a developer comment (invisible in the wiki).</summary>
    /// <summary>extraField: one `key: value` line that goes into the front
    /// matter's explicit `extra:` block (Zola 0.23 puts only that block into
    /// page.extra — loose top-level keys are ignored by the front-matter
    /// deserializer).</summary>
    public static string Header(string title, string description, string source, string extraField = null)
    {
        // Zola content front matter is YAML (not TOML). Titles can be client display
        // names, so escape the double-quoted scalar properly.
        var extraYaml = extraField is null ? "" : $"extra:\n  {extraField}\n";
        return $$"""
            ---
            title: "{{Yaml(title)}}"
            description: "{{Yaml(description)}}"
            {{extraYaml}}---

            <!-- Generated by tools/generate from the live database (source: {{source}}).
                 Do not edit by hand; regenerate instead. -->
            """;
    }

    private static string Yaml(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Zone display name: the client's name where it has one, otherwise the
    /// internal zone name (gamma zones have no client name).</summary>
    public static string ZoneName(string name) => ClientStrings.TryGetValue(name, out var d) ? d : name;

    /// <summary>Engineering-style number: 214 stays "214", 1000 becomes "1k", 1001 becomes
    /// "1.001k" — at most three decimals with trailing zeros trimmed, k/M/G above 10³.
    /// Values below 1000 (and fractions) are left untouched.</summary>
    public static string Num(long v)
    {
        if (v < 0) return "-" + Num(-v);
        if (v < 1000) return v.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var (unit, suf) = v >= 1_000_000_000 ? (1_000_000_000L, "G") : v >= 1_000_000 ? (1_000_000L, "M") : (1000L, "k");
        var d = (double)v / unit;
        return d.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture) + suf;
    }

    /// <summary>Stat values: engineering notation above 1000, up to six decimals below it.</summary>
    public static string Num(double v)
    {
        if (v < 0) return "-" + Num(-v);
        if (v >= 1000) return Num((long)Math.Round(v));
        return v.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
    }

    /// <summary>Player-readable name for an internal definition/zone name: the client's
    /// own string when the dictionary has it, otherwise derived from the internal name.
    /// forceDerived skips the dictionary (used when a client string collides with
    /// another item's name and the derived name is more informative).</summary>
    /// <summary>URL-safe on-page anchor id for a display name
    /// (e.g. "Praetorian Gropho" -> "praetorian-gropho").</summary>
    public static string Slug(string text)
    {
        var sb = new StringBuilder(text.Length);
        foreach (var c in text.ToLowerInvariant())
        {
            if (c is >= 'a' and <= 'z' or >= '0' and <= '9')
                sb.Append(c);
            else if (sb.Length > 0 && sb[^1] != '-')
                sb.Append('-');
        }
        return sb.ToString().TrimEnd('-');
    }

    /// <summary>Scroll link to a robot family on the robots catalog page
    /// (mirrors RobotsPage.FamilyKey, so the anchor always exists).</summary>
    public static string RobotAnchorUrl(string defname)
        => "/content/robots/#" + Slug(DisplayName(defname.Replace("_mk2", "").Replace("_reward1", "")));

    public static string DisplayName(string name, bool forceDerived = false)
    {
        if (!forceDerived && ClientStrings.TryGetValue(name, out var client)) return client;
        return Derive(name);
    }

    private static string Derive(string name)
    {
        if (name.StartsWith("def_")) name = name[4..];
        if (name.StartsWith("extcat_")) name = name[7..];
        if (name.StartsWith("ext_")) name = name[4..];
        if (name.EndsWith("_bot")) name = name[..^4];
        name = name.Replace("_mk2", " MK2").Replace("_reward1", " (reward)").Replace("_CT_capsule", " (CT capsule)");
        var tokens = name.Split('_', StringSplitOptions.RemoveEmptyEntries);
        var outTokens = new List<string>();
        foreach (var t in tokens)
        {
            // the internal tier tokens (named1/2/3/4) are not player language —
            // the client tier badges are T2/T3/T4/T5 (the tierlevel), so render
            // them as such: "Named1 Adaptive Alloy" -> "T2 Adaptive Alloy"
            if (t is "named1" or "named2" or "named3" or "named4")
            {
                if (outTokens.Count > 0 && outTokens[^1] is "T2" or "T3" or "T4" or "T5")
                    continue; // e.g. ..._named1_named2_... would double up
                outTokens.Add(t switch { "named1" => "T2", "named2" => "T3", "named4" => "T5", _ => "T4" });
                continue;
            }
            outTokens.Add(char.ToUpperInvariant(t[0]) + t[1..]);
        }
        return string.Join(' ', outTokens);
    }
}

