namespace Perpetuum.WikiGenerate;

/// <summary>Markdown table + page helpers shared by all page generators.</summary>
public static class Md
{
    /// <summary>Client display names: a static snapshot of the official client's
    /// English string dictionary (see ClientNames.cs), reduced to the definition
    /// and zone keys this generator resolves.</summary>
    public static IReadOnlyDictionary<string, string> ClientStrings { get; } = ClientNames.Map;

    /// <summary>Escapes pipes and newlines for a single table cell.</summary>
    public static string Cell(object? v)
    {
        var s = Genxy.FormatValue(v);
        if (s.Length == 0) return "–";
        return s.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
    }

    public static void WriteTable(StringBuilder sb, string[] header, params string[][] rows)
    {
        sb.Append('|');
        foreach (var h in header) sb.Append(' ').Append(h).Append(" |");
        sb.Append('\n');
        sb.Append('|');
        for (var i = 0; i < header.Length; i++) sb.Append("---|");
        sb.Append('\n');
        foreach (var row in rows)
        {
            sb.Append('|');
            foreach (var c in row) sb.Append(' ').Append(Cell(c)).Append(" |");
            sb.Append('\n');
        }
    }

    public static string Tier(int tierType, int? tierLevel)
    {
        if (tierLevel is null || tierLevel == 0) return tierType == 2 ? "prototype" : "";
        return tierLevel.ToString();
    }

    /// <summary>Standard page header. Provenance is a developer comment (invisible in the wiki).</summary>
    public static string Header(string title, string description, string source)
    {
        // Zola content front matter is YAML (not TOML). Titles can be client display
        // names, so escape the double-quoted scalar properly.
        return $$"""
            ---
            title: "{{Yaml(title)}}"
            description: "{{Yaml(description)}}"
            ---

            <!-- Generated by tools/generate from the live database (source: {{source}}).
                 Do not edit by hand; regenerate instead. -->
            """;
    }

    private static string Yaml(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Zone display name: the client's name where it has one, otherwise the
    /// internal zone name (gamma zones have no client name).</summary>
    public static string ZoneName(string name) => ClientStrings.TryGetValue(name, out var d) ? d : name;

    /// <summary>Engineering-style number: 214 stays "214", 1000 becomes "1k", 1001 becomes
    /// "1.001k" — at most three decimals with trailing zeros trimmed, k/M/G above 10³.
    /// Values below 1000 (and fractions) are left untouched.</summary>
    public static string Num(long v)
    {
        if (v < 0) return "-" + Num(-v);
        if (v < 1000) return v.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var (unit, suf) = v >= 1_000_000_000 ? (1_000_000_000L, "G") : v >= 1_000_000 ? (1_000_000L, "M") : (1000L, "k");
        var d = (double)v / unit;
        return d.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture) + suf;
    }

    /// <summary>Stat values: engineering notation above 1000, up to six decimals below it.</summary>
    public static string Num(double v)
    {
        if (v < 0) return "-" + Num(-v);
        if (v >= 1000) return Num((long)Math.Round(v));
        return v.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture);
    }

    /// <summary>Player-readable name for an internal definition/zone name: the client's
    /// own string when the dictionary has it, otherwise derived from the internal name.
    /// forceDerived skips the dictionary (used when a client string collides with
    /// another item's name and the derived name is more informative).</summary>
    /// <summary>URL-safe on-page anchor id for a display name
    /// (e.g. "Praetorian Gropho" -> "praetorian-gropho").</summary>
    public static string Slug(string text)
    {
        var sb = new StringBuilder(text.Length);
        foreach (var c in text.ToLowerInvariant())
        {
            if (c is >= 'a' and <= 'z' or >= '0' and <= '9')
                sb.Append(c);
            else if (sb.Length > 0 && sb[^1] != '-')
                sb.Append('-');
        }
        return sb.ToString().TrimEnd('-');
    }

    /// <summary>Scroll link to a robot family on the robots catalog page
    /// (mirrors RobotsPage.FamilyKey, so the anchor always exists).</summary>
    public static string RobotAnchorUrl(string defname)
        => "/content/robots/#" + Slug(DisplayName(defname.Replace("_mk2", "").Replace("_reward1", "")));

    public static string DisplayName(string name, bool forceDerived = false)
    {
        if (!forceDerived && ClientStrings.TryGetValue(name, out var client)) return client;
        return Derive(name);
    }

    private static string Derive(string name)
    {
        if (name.StartsWith("def_")) name = name[4..];
        if (name.StartsWith("extcat_")) name = name[7..];
        if (name.StartsWith("ext_")) name = name[4..];
        if (name.EndsWith("_bot")) name = name[..^4];
        name = name.Replace("_mk2", " MK2").Replace("_reward1", " (reward)").Replace("_CT_capsule", " (CT capsule)");
        var tokens = name.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Join(' ', tokens.Select(t => char.ToUpperInvariant(t[0]) + t[1..]));
    }
}

