#!/usr/bin/env python3
"""Lay out the recipes page as category sections of item cards.

One-shot transform of the committed generated page (no database needed): it
reads tools/recipes_data.json (written by tools/gen_production_pages.py,
which parsed the original component table) and rewrites content/content/
recipes.md as:

  * a chip index of the top-level categories (like the missions page)
  * one section per category / sub-category
  * one card per craftable item in the same layout as the mission reward
    cards (.mission-cards / .mission-card / .reward-box): the item name
    linked to its own page, the research level, and one reward-box row per
    component (linked to the component's item or ore page)

The original table is NOT kept — tools/recipes_data.json is the data cache
the production-section tool falls back to. The long-term source of this page
is the .NET generator (RecipesPage.cs) — keep the two in sync.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "recipes_data.json")
RECIPES = os.path.join(ROOT, "content", "content", "recipes.md")

# top-level category order (mirrors ItemsPage.Categories in the .NET generator);
# anything else (bots, internal robot parts, ...) -> Other
CAT_ORDER = ["Modules", "Ammo", "Robot parts", "Materials", "Production",
             "Mission items", "Artifacts", "Decorations", "Special & other"]


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def derived_name(definition: str) -> str:
    words = definition[len("def_"):].split("_")
    return " ".join(w.capitalize() if w.isalpha() else w for w in words)


def slug_of(definition: str) -> str:
    return definition[len("def_"):].lower().replace("_", "-")


def main():
    data = json.load(open(DATA, encoding="utf-8"))
    recipes = {k: ([(c, q) for c, q in v["components"]], v["research"])
               for k, v in data["recipes"].items()}
    items, ores = data["items"], data["ores"]
    if not recipes:
        print("error: no recipe data — run tools/gen_production_pages.py first")
        return 1

    def item_html(defn):
        if defn in items:
            return f'<a href="{items[defn]["url"]}">{esc(items[defn]["name"])}</a>'
        if defn in ores:
            return f'<a href="{ores[defn]["url"]}">{esc(ores[defn]["name"])}</a>'
        return esc(derived_name(defn))

    def title_html(defn):
        if defn in items:
            return f'<a href="{items[defn]["url"]}">{esc(items[defn]["name"])}</a>'
        return esc(derived_name(defn))

    def cat_of(defn):
        if defn in items:
            return items[defn]["category"]
        return "Other"

    # group: (top, sub) -> [def, ...]
    groups = {}
    for defn in recipes:
        top, _, sub = cat_of(defn).partition(" / ")
        groups.setdefault((top if top in CAT_ORDER else "Other", sub), []).append(defn)

    def anchor(s):
        return "#" + re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

    # frontmatter of the existing page
    txt = open(RECIPES, encoding="utf-8").read()
    m = re.match(r"^---\n.*?\n---\n", txt, re.S)
    front = m.group(0) if m else '---\ntitle: "Recipes"\n---\n'

    sb = [front,
          "<!-- Generated by tools/generate from the live database (source: components, itemresearchlevels (joined to entitydefaults)).",
          "     Do not edit by hand; regenerate instead. -->",
          "",
          "# Recipes",
          "",
          "Component requirements for every item that is assembled from other items, grouped by category "
          "(see [Production](/features/production/) in the features section). **Research level** is the maximum "
          "research level the item has — higher levels change yield/calibration, not the component list. "
          "Each item has its own page with its stats, the items it is a component of, and the vendors that sell it.",
          ""]

    tops = []
    for top, _sub in groups:
        if top not in tops:
            tops.append(top)
    tops.sort(key=lambda t: CAT_ORDER.index(t) if t in CAT_ORDER else 99)
    # Plain markdown links would not render inside the HTML block (Zola only
    # runs the markdown parser on text, not on HTML), so these are real anchors.
    sb.append('<div class="mission-index">\n' +
              " ".join(f'<a href="{anchor(t)}"><span class="mission-type-chip">{esc(t)}</span></a>&ensp;' for t in tops)
              + "\n</div>\n")

    # ordered sections
    order = sorted(groups.items(),
                   key=lambda kv: (CAT_ORDER.index(kv[0][0]) if kv[0][0] in CAT_ORDER else 99,
                                   kv[0][0] == "Other", kv[0][1]))
    last_top = None
    for (top, sub), defs in order:
        if top != last_top:
            last_top = top
            sb.append(f"\n## {top}\n")
        if sub:
            sb.append(f"\n### {sub} ({len(defs)})\n")
        sb.append('\n<div class="mission-cards">\n')
        for defn in sorted(defs):
            comps, research = recipes[defn]
            sb.append('<div class="mission-card">\n')
            sb.append('<div class="mission-card-head">\n')
            sb.append('<span class="icon-mask mission-card-icon" role="img" aria-label="item icon"></span>\n')
            sb.append("<div><div class=\"mission-card-title\">" + title_html(defn) + "</div>")
            if research not in ("–", ""):
                sb.append(f'<div class="mission-card-sub">Research level {research}</div>')
            sb.append("</div>\n</div>\n")
            sb.append('<div class="mission-card-rewards">\n')
            for comp, qty in sorted(comps):
                sb.append(
                    f'<div class="reward-box"><span class="icon-mask reward-box-icon" role="img" '
                    f'aria-label="item icon"></span> {item_html(comp)} ×{qty}</div>\n')
            sb.append("</div>\n</div>\n")
        sb.append("</div>\n")

    open(RECIPES, "w", encoding="utf-8").write("\n".join(sb))
    cards = sum(len(d) for d in groups.values())
    print(f"recipes page rewritten: {len(groups)} sections, {cards} cards")
    return 0


if __name__ == "__main__":
    sys.exit(main())
